config/routes.rb
# Guidelines, rules, other pages, etc. tells it where to go
Rails.application.routes.draw do  

  root to: 'home#show'
  get "/about" => "static#about"
  get "/contact" => "static#contact"
  get "/info" => "static#info"
  get "/terms" => "static#terms"
  get "/privacy" => "static#privacy"
  get "/rules" => "static#rules"
  
  scope path: 'admin' do
    authenticate :user, lambda { |u| u.admin? } do
      mount RailsEmailPreview::Engine, at: 'emails'
    end
  end

  get '/users/block/:id' => 'users#block_user'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  mount Thredded::Engine => '/forum'
  
  resources :tips

  match '/tip-moderation',     to: 'tips#moderation', via: 'get'
  
  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  
end

app/models/tip.rb
class Tip < ActiveRecord::Base
    
    belongs_to :topic
    belongs_to :subtopic
    
    validates :title,
    presence: true,
    length: {maximum: 45},
    on: :create,
    allow_nil: false
    
    validates :body,
    presence: true,
    length: {maximum: 500},
    on: :create,
    allow_nil: false
    
    validates :topic_id,
    presence: true,
    on: :create,
    allow_nil: false
   
    validates :subtopic_id,
    presence: true,
    on: :create,
    allow_nil: false 
   
    def self.search(term)
        if term
            where('title LIKE ?', "%#{term}%").or(where('body LIKE ?', "%#{term}%")) #.order('id DESC')
        else
            all
        end
    end
   
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  
  def index
    @tips = Tip.search(params[:term])
    @tip = Tip.new
  end

  # def new
  #   # @tips = Tip.all
  #   # @tip = Tip.new
  # end

  def create
    @tip = Tip.new(tip_params)
    if @tip.save
        redirect_to "/tips", alert: "Advice submitted! It will be visible after its been reviewed by a moderator. Check back soon!"
    else
        redirect_to "/tips", alert: "Error submitting advice."
        # maybe change to new_user_path
    end
  end

  def show
    @tips = Tip.find(params[:id])
  end
  # params[:id] 
  
  def destroy
    if current_user.admin
      @tips = Tip.find(params[:id])
      @tips.destroy
      redirect_to "/tip-moderation", notice: "Tip deleted successfully."
    else
      redirect_to "/tips", alert: "An error occurred while trying to delete tip."
    end
  end
  
  def update
    # run_callbacks(:approve) do
    if current_user.admin
        @tips = Tip.find(params[:id])
        @tips.update_attribute(:approved, 'true')
        redirect_to "/tip-moderation", notice: "Tip approved successfully."
    else
      redirect_to "/tips", alert: "An error occurred while trying to approve tip."
    end
  end
  
  def moderation
    @tips = Tip.all
  end
  
  def tip_params
    params.require(:tip).permit(:title, :body, :topic_id, :subtopic_id, :term)
  end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_nav.html.erb
<% current_uri = request.env['PATH_INFO'] %>
<nav class="tips--moderation-navigation">
    <div class="tips--moderation-navigation--items">
        <%= form_tag(tips_path, method: :get) do %>
            <%= text_field_tag :term, nil, placeholder: "Search tips" %>
            <%= submit_tag 'Search', name: nil, id: "submit-button" %>
        <% end %>
        <% if current_uri != "/tips" %>
            <div id="nav-link"><%= link_to "Back", "/tips" %></div>
        <% end %>
        <% if current_uri != "/tip-moderation" %>
            <% if current_user.admin %> 
                <div id="nav-link"><%= Tip.where(approved: false).count %> tips in <%= link_to "moderation", "/tip-moderation" %> queue</div>
            <% end %>
        <% end %>
    </div>
</nav>

app/views/tips/create.html.erb
<h1>Tips</h1>

app/views/tips/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

<%= render 'nav' %>

<div align="center">
    <h1>Rick's Tips</h1>
</div>
<% subjects = @tips.select(:topic_id).distinct.where(approved: true).order(topic_id: :asc) %>
<% if subjects.length == 0 %>
    <h2 align="center">Sorry, we couldn't find any tips</h2>
<% else %>
<div id="tip-main-header">
    <h1><span id="count"><%= @tips.where(approved: true).count %></span> Tips Available</h1>
</div>
    <% subjects.each do |subject| %>
        <div>
            <div class="tip-dropdown">
                <h2 id="first" class="tip-header">
                    <%= subject.topic.name %>
                    <div class="tip-dropdown-button"><i class="material-icons md-36">keyboard_arrow_right</i></div>
                </h2>
                <div class="tip-minimize-window">
                    <% subject_details = subjects.select(:subtopic_id).distinct.order(subtopic_id: :asc) %><!--.limit(10)-->
                    <% subject_details.each do |subject_detail| %>
                        <% if subject_detail.topic_id == subject.topic_id %>
                            <ul class="tip-detail-list">
                                <li>
                                    <h2 id="second" class="tip-header">
                                        <%= subject_detail.subtopic.name %>
                                        <div class="tip-dropdown-button"><i class="material-icons md-36">keyboard_arrow_right</i></div>
                                    </h2>
                                    <div class="tip-minimize-window">
                                        <% tips = @tips.where(approved: true).where(topic_id: subject.topic_id).where(subtopic_id: subject_detail.subtopic_id) %>
                                        <% tips.each do |tip| %>
                                            <ul class="tip-detail-list">
                                                <li>
                                                    <h2 id="third" class="tip-header">
                                                        <%= tip.title.split.map(&:capitalize)*' ' %>
                                                        <div class="tip-dropdown-button"><i class="material-icons md-36">keyboard_arrow_right</i></div>
                                                    </h2>
                                                    <ul class="tip-individual-list">
                                                        <li>
                                                            <div id="tip-body">
                                                                <%= tip.body %>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        <% end %>
                                    </div>
                                </li>
                            </ul>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

<div id="tip-bottom"></div>

<div class="tip-blurb">
    <h1 align="center">What are Rick's Tips?</h1>
    <p>Do you have any tips or advice that you think could help someone somewhere? We want this to be a place you can put it. Rick's Tips are our own constantly evolving resource that is continuously being built by YOU the community. We want Rick's Tips to be a platform for our community member's voice's to be heard. Each tip submitted is completely anonymous, like the rest of Extinguish, and reviewed by one of our moderators before it is sorted and displayed to keep our tips as helpful as possible.</p>
    <p>If you have any suggestions for new tip topics or subtopics feel free to <%= link_to 'contact us', "/contacts/new" %>!</p>
    
</div>

<div align="center">
    <h1 style=" margin-bottom: 0">Submit a new tip!</h1>
</div>

<%= form_for @tip do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, placeholder: 'Ex. "Walk In Groups"', :required => true, maxlength: 45, id: "title" %>
    <div id="form" style="display: none;">
        <%= f.label :body, "Content"%>
        <%= f.text_area :body, placeholder: 'Ex. "Even when you are close to home always walk in groups at night."', :required => true, maxlength: 500 %>
        <div class="field">
            <%= f.label :topic_id %>
            <%= f.collection_select :topic_id, Topic.order(:id), :id, :name, include_blank: false, include_blank: "Please select a topic" %>
        </div>
        <div class="field">
            <%= f.label :subtopic_id, "Subtopic" %>
            <%= f.grouped_collection_select :subtopic_id, Topic.order(:id), :subtopics, :name, :id, :name, :required => true, include_blank: true %>
        </div>
        <%= submit_tag "Submit" %>
    </div>
<% end %>

<script>
$(".tip-header").click(function(){
    if($(this.children[0]).html() == '<i class="material-icons md-36">keyboard_arrow_right</i>'){
        $(this.children[0]).html('<i class="material-icons md-36">keyboard_arrow_down</i>');
    }
    else{
        $(this.children[0]).html('<i class="material-icons md-36">keyboard_arrow_right</i>');
    }
    $(this.parentNode.children[1]).slideToggle();
});

$("#title").focus(function(){
    $("#form").slideDown();
});

jQuery(function() {
  var subtopics;
  $('#tip_subtopic_id').parent().hide();
  subtopics = $('#tip_subtopic_id').html();
  console.log(subtopics);
  return $('#tip_topic_id').change(function() {
    var topic, escaped_topic, options;
    topic = $('#tip_topic_id :selected').text();
    escaped_topic = topic.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g, '\\$1');
    options = $(subtopics).filter("optgroup[label=" + escaped_topic + "]").html();
    console.log(options);
    if (options) {
      $('#tip_subtopic_id').html(options);
      return $('#tip_subtopic_id').parent().show();
    } else {
      $('#tip_subtopic_id').empty();
      return $('#tip_subtopic_id').parent().hide();
    }
  });
});
</script>

app/views/tips/moderation.html.erb
<%= render 'nav' %>
<% if !current_user.admin? %>
  <p class="thredded--alert thredded--alert-warning">You are not authorized to view this content</p>
<% else %>
<div align="center">
<h1>Tip Moderation Queue</h1>

<% if (Tip.where(approved: false).count) == 0  %>
    <h2>Woo! The tip moderation queue is empty!</h2>
    </div>
<% else %>
</div align="center">
<% @tips.where(approved: false).each do |tip| %>

                <ul id="tip-moderation-list" align="center">
                <li><h2><%= tip.title %></h2>
                <li><h3><%= tip.body %></h3></li>
                <li><%= tip.topic.name %> > <%= tip.subtopic.name %></li>
                <div align="center" style="display: inline-flex;">
                <%= button_to "Delete Tip", tip_path(tip), data: { confirm: "Are you sure you want to delete this tip? This CANNOT be undone." }, method: :delete, :class => "table-button"%>
                <%= button_to "Approve Tip", tip_path(tip), method: :put,  :class => "table-button"%>
                </div>
                </ul>
<% end %>
</div>
<% end %>
<% end %>

app/views/tips/new.html.erb
<% controller.redirect_to root_path %>
<div align="center">
<p class="thredded--alert thredded--alert-warning">You are not authorized to view this content</p>
</div>
    

        

app/views/tips/show.html.erb
<h1>Tips</h1>



<%= link_to "Back", "/tips" %>

<!--maybe change back to users_path -->